### ISSUE TITLE
Explorer links doesn't work at all

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/mobile-wallet#214]
Version: Android production app

Steps:
- go to Account details
- try click "Show account in the Block Explorer"

or

- go to the transaction list
- show transaction detail
- Click "Show in the Block Explorer"

Result:
No reaction. Explorer won't open.

Expected result:
Open explorer with either account data (account view) or transaction details (transaction view)

**Comment by bassemmagdy** [comment]
could be a bit laggy from the block-explorer side as the loading page needs to be improved. I tested it a couple of times and it worked, latest dev branch works on android, latest ios app from the app store does it too.

**Comment by cryptoBeliever** [comment]
@bassemmagdy I don't think it's laggy explorer case. When I click "Show account in the Block Explorer" nothing happens at all. I'm not redirected to browser after a few minutes. Please investigate more.

Android, Samsung S20

**Comment by OlegMakarenko** [comment]
Please check if the explorer url is set in ENV

**Comment by cryptoBeliever** [comment]
Fixed.
