### ISSUE TITLE
Additional warning for aggregate bonded announced by "third party" address. Add Transaction Graphic

### ISSUE THREAD

**Issue by coiki** [symbol/mobile-wallet#222]
Reason:

Scammers are sending aggregate bonded requesting all funds to random addresses (transaction is initialized from a "third-party" wallet). For example:
http://explorer.symbolblockchain.io/transactions/7BE1EB498B914BDA7F17C26789711E62276280F6322A8C3F36A9E60CD878C9B6

We should add a warning (after pop up with password) - double confirmation - to ask the user if he really wants to send this transaction because it was initialized by the third-party wallet.

We should warn if account which initialized tx is not related to an account that is signing (we should not warn if another cosigner from the same multi- initialized the transaction).

There are some legit bonded initialized by "third-party" accounts like those send by All nodes or nember.art and in future we should maybe do some "whitelist" of addresses.

(From Desktop's #1719)

**Comment by coiki** [comment]
let's check if this is duplicate of #222

**Comment by OlegMakarenko** [comment]
Fixed in `dev` branch.
