### ISSUE TITLE
Update typescript Symbol SDK to 1.0.3

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/mobile-wallet#249]
Update to SDK 1.0.2 should be without changes on wallet side but we need to do a regression of the wallet.

Changelog:
https://github.com/symbol/symbol-sdk-typescript-javascript/releases/tag/v1.0.2

**Comment by cryptoBeliever** [comment]
There is already 1.0.3 SDK

**Comment by OlegMakarenko** [comment]
Merged into `main`.
