### ISSUE TITLE
Send form - fee selector problems when recipient address is not provided

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/mobile-wallet#254]
Steps:
1. From the home page choose "Send" (address is not selected)
2. **First issue**: Slow/Recommended/Fast fees have fixed values (not calculated). It should be calculated. If we need an address we can use some "fake" address to calculate real fees.
3. **Second issue**: Choose fee selector and switch Fee to "Slow". The selector is spinning all the time.

Expected results:
Fee selector should calculate "real" fees and should not hang without address.

**Comment by OlegMakarenko** [comment]
@bassemmagdy https://github.com/symbol/mobile-wallet/pull/237#discussion_r732544853

We can get the signer publicKey of Nemesis block and use it as a dummy account to calculate the fees
