### ISSUE TITLE
Wallet backup got broken file

### ISSUE THREAD

**Issue by NikoCyber** [symbol/mobile-wallet#284]
WTR:

1. Backup existing wallet
2. Open .pdf file

Result: the file is broken

**Comment by cryptoBeliever** [comment]
Steps:

1. Add at least one additional account
2. Do PDF backup

Result:
All pages (except first one) are presented incorrectly (without QR'codes, private keys and valid addresses)

**Comment by OlegMakarenko** [comment]
Fixed in the: https://github.com/symbol/wallets-lib/pull/4
Awaiting test and review.

**Comment by OlegMakarenko** [comment]
Merged into `main`.
