### ISSUE TITLE
Remove all dashes from addresses

### ISSUE THREAD

**Issue by coiki** [symbol/mobile-wallet#296]
## Background

We want to adopt standards that make Symbol easier to use. We have seen that the dashes in the addresses don’t really help and people don’t really understand them. It also adds complexity when creating a Symbol app.

## Acceptance Criteria

AC1. Remove dashes from all addresses all across the app.

**Comment by cryptoBeliever** [comment]
In such case, https://github.com/symbol/mobile-wallet/issues/241 will be not relevant anymore. Closed.

**Comment by cryptoBeliever** [comment]
Fixed in 1.4.1
