### ISSUE TITLE
See the full address on transactions

### ISSUE THREAD

**Issue by Peersyst** [symbol/mobile-wallet#90]
A user wrote this:

"We cannot see the full address from the transaction history, so we need to open the explorer to get it. This is so inconvenient. At least, I would like to copy sender address from history. Furthermore, I think it would be better if we could resister the address into address book directly from history. And, also better to be able to make transaction directly from history!( like Email reply) thanks"

Would be nice to display the address with a copy button and maybe add the button to register directly the contact

**Comment by OlegMakarenko** [comment]
related: #23

**Comment by coiki** [comment]
### User Story

As a user reviewing the details of a past transaction,
I want to see all the information correctly displayed, including signer and recipient's addresses,
so I can correctly identify all transactions in my wallet

### Acceptance Criteria
**AC1.** I can correctly see all involved addresses when I'm reviewing the details of a past transaction.
**AC2.** When I tap on an address, it will get copied to my clipboard and I will be notified.
